# Generated by Django 5.1 on 2024-09-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='id_photo',
            field=models.ImageField(blank=True, upload_to='Id_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(max_length=100),
        ),
    ]
