services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn traffic_management.wsgi
    # Background worker command
    workerCommand: python manage.py process_tasks