# Generated by Django 5.1 on 2024-09-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=255)),
                ('mask_points', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('road_1image', models.ImageField(upload_to='output_frames/')),
                ('road_2image', models.ImageField(upload_to='output_frames/')),
                ('road_3image', models.ImageField(upload_to='output_frames/')),
                ('road_4image', models.ImageField(upload_to='output_frames/')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLightState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow')], max_length=10)),
                ('countdown_timer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='videos/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
