# Generated by Django 5.1 on 2024-09-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('road1', models.ImageField(upload_to='output_frame/')),
                ('road2', models.ImageField(upload_to='output_frame/')),
                ('road3', models.ImageField(upload_to='output_frame/')),
                ('road4', models.ImageField(upload_to='output_frame/')),
            ],
        ),
        migrations.CreateModel(
            name='Road2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('road1', models.ImageField(upload_to='output_frame/')),
                ('road2', models.ImageField(upload_to='output_frame/')),
                ('road3', models.ImageField(upload_to='output_frame/')),
                ('road4', models.ImageField(upload_to='output_frame/')),
            ],
        ),
        migrations.CreateModel(
            name='Road3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('road1', models.ImageField(upload_to='output_frame/')),
                ('road2', models.ImageField(upload_to='output_frame/')),
                ('road3', models.ImageField(upload_to='output_frame/')),
                ('road4', models.ImageField(upload_to='output_frame/')),
            ],
        ),
    ]
