# Generated by Django 5.1 on 2024-09-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_road1_road2_road3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Road2',
            new_name='Road',
        ),
        migrations.DeleteModel(
            name='Road1',
        ),
        migrations.DeleteModel(
            name='Road3',
        ),
    ]
