# Generated by Django 5.1 on 2024-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_rename_road2_road_delete_road1_delete_road3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='road1',
        ),
        migrations.RemoveField(
            model_name='road',
            name='road2',
        ),
        migrations.RemoveField(
            model_name='road',
            name='road3',
        ),
        migrations.RemoveField(
            model_name='road',
            name='road4',
        ),
        migrations.AddField(
            model_name='road',
            name='time_in_sec',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
