# Generated by Django 5.1 on 2024-12-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_remove_road_road1_remove_road_road2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='road',
            old_name='name',
            new_name='road_name',
        ),
    ]
