# Generated by Django 5.1 on 2024-12-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_rename_name_road_road_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticTime120',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('avg_time', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StaticTime240',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('avg_time', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StaticTime30',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('avg_time', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StaticTime60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('avg_time', models.IntegerField(max_length=10)),
            ],
        ),
    ]
