# Generated by Django 5.1 on 2024-12-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_statictime120_statictime240_statictime30_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_name', models.CharField(max_length=30)),
                ('data', models.JSONField()),
                ('avg_time', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='StaticTime120',
        ),
        migrations.DeleteModel(
            name='StaticTime240',
        ),
        migrations.DeleteModel(
            name='StaticTime30',
        ),
        migrations.DeleteModel(
            name='StaticTime60',
        ),
    ]
