# Generated by Django 5.1 on 2024-12-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_statictime_delete_statictime120_delete_statictime240_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='maskforplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=10)),
                ('mask', models.JSONField()),
            ],
        ),
    ]
