# Generated by Django 5.1 on 2024-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_maskforplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='numberplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('num_plate', models.CharField(max_length=9)),
            ],
        ),
    ]
