# Generated by Django 5.1 on 2024-12-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0009_numberplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='phone_number',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
