# Generated by Django 5.1 on 2024-12-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0010_numberplate_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='person_name',
            field=models.CharField(default='shidharth', max_length=30),
            preserve_default=False,
        ),
    ]
