# Generated by Django 5.1 on 2024-12-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0013_chalan'),
    ]

    operations = [
        migrations.CreateModel(
            name='uter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
